#!/usr/bin/env node
/**
 * Cross-prepare a macOS distribution from Windows.
 *
 * Windows can't create the framework symlinks an Electron .app bundle needs,
 * so we can't fully assemble the .app here. Instead we ship the user a
 * three-piece kit and a one-shot bash installer that runs on their Mac:
 *
 *   - app.asar                  (this Windows build's renderer + engine + electron sources)
 *   - build/icon.icns           (the macOS icon)
 *   - veloxa-mac-installer.sh   (downloads Electron-darwin from electronjs.org and
 *                                stitches everything into a runnable .app)
 *   - README-mac.txt            (3-line user-facing install instructions)
 *
 * Output: release/VeloxaWatermarkStudio-mac-{version}.tar.gz (single file).
 *
 * Run with: node scripts/build-mac.js
 */
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { spawnSync } = require('node:child_process');

const projectRoot = path.resolve(__dirname, '..');
const releaseDir  = path.join(projectRoot, 'release');
const buildDir    = path.join(projectRoot, 'build');
const pkg         = require(path.join(projectRoot, 'package.json'));
const version     = pkg.version;
const ELECTRON_DEP = (pkg.devDependencies && pkg.devDependencies.electron) || '';
const ELECTRON_VERSION = ELECTRON_DEP.replace(/^[\^~]/, '');

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { stdio: 'inherit', shell: process.platform === 'win32', ...opts });
  if (r.status !== 0) {
    console.error(`✘ \`${cmd} ${args.join(' ')}\` exited with status ${r.status}`);
    process.exit(r.status || 1);
  }
}

console.log(`Veloxa macOS package builder — v${version}`);
console.log(`Electron runtime version target: v${ELECTRON_VERSION}`);

if (!ELECTRON_VERSION) {
  console.error('✘ Could not read Electron version from package.json devDependencies.electron');
  process.exit(1);
}

// 1. Ensure icons (icon.icns specifically — generated by scripts/generate-icon.js).
const icnsPath = path.join(buildDir, 'icon.icns');
if (!fs.existsSync(icnsPath)) {
  console.log('build/icon.icns missing — generating…');
  run(process.execPath, [path.join(__dirname, 'generate-icon.js')]);
}

// 2. Vite build (in case dist/ is stale).
console.log('');
console.log('▸ Vite renderer build');
run('npm', ['run', 'build']);

// 3. Run @electron/packager for win32 just to produce a clean, fresh asar
//    that has the exact bundle layout we want. The .app step happens on the
//    user's Mac via veloxa-mac-installer.sh.
//
//    Stage in the OS temp dir rather than `release/mac-stage/` so the
//    --out= path doesn't include the project's "0 AI/Claude/..." spaces,
//    which the shell parses as argument separators.
console.log('');
console.log('▸ Packaging app.asar via @electron/packager (win32 host build)');
const winOut = path.join(os.tmpdir(), `veloxa-mac-stage-${Date.now()}`);
fs.mkdirSync(winOut, { recursive: true });
// Aggressive ignore list: keep ONLY what the runtime actually needs.
// Without these, packager copies every byte of release/, tests/, .git/,
// src/, build/, etc. into the asar — the previous Win .exe install pulled
// itself in recursively (774 MB).
//
// Use the @electron/packager Node API directly rather than the CLI: the
// CLI route forces these regex strings through cmd.exe, which mangles the
// `(` `|` `$` chars. Node API takes RegExp objects cleanly.
const PACKAGER_IGNORES = [
  /^\/release(\/|$)/,
  /^\/tests(\/|$)/,
  /^\/scripts(\/|$)/,
  /^\/src(\/|$)/,
  /^\/build(\/|$)/,
  /^\/\.git(\/|$)/,
  /^\/\.claude(\/|$)/,
  /^\/\.vscode(\/|$)/,
  /^\/INSTALL\.md$/,
  /^\/README\.md$/,
  /^\/\.gitignore$/,
  /^\/\.gitattributes$/,
  /^\/postcss\.config\.js$/,
  /^\/tailwind\.config\.js$/,
  /^\/vite\.config\.js$/,
  /^\/index\.html$/,
  /\.tmp(\.|$)/,           // stray *.tmp.* test artifacts in repo root
  /^\/\.npmrc$/,
];

// Use the programmatic API directly. The packager async-returns the output
// dir path(s); we await it inline since we're already inside an async-ish
// flow (just block on the promise via a tiny await wrapper).
(async function packagerStep() {
  const packager = require('@electron/packager');
  const fn = packager.packager || packager.default || packager;
  const result = await fn({
    dir: projectRoot,
    name: 'veloxa-asar-host',
    platform: 'win32',
    arch: 'x64',
    out: winOut,
    overwrite: true,
    asar: true,
    prune: true,
    ignore: PACKAGER_IGNORES,
  });
  console.log('Packager wrote:', Array.isArray(result) ? result[0] : result);
})().then(continueBuild, (err) => {
  console.error('✘ packager failed:', err);
  process.exit(1);
});

function continueBuild() {
const asarSrc = path.join(winOut, 'veloxa-asar-host-win32-x64', 'resources', 'app.asar');
if (!fs.existsSync(asarSrc)) {
  console.error('✘ packager did not produce app.asar at expected path:', asarSrc);
  console.error('  Contents of staging dir:');
  try { fs.readdirSync(winOut).forEach(f => console.error('   ', f)); } catch {}
  process.exit(1);
}

// 4. Update the install script to embed the EXACT Electron version pin so
//    the user's runtime matches what we built against. (sed-style replace
//    via Node so we don't depend on platform tools.)
const installerSrcPath = path.join(projectRoot, 'scripts', 'veloxa-mac-installer.sh');
let installerSrc = fs.readFileSync(installerSrcPath, 'utf8');
installerSrc = installerSrc.replace(
  /^ELECTRON_VERSION=".*"$/m,
  `ELECTRON_VERSION="${ELECTRON_VERSION}"`,
);

// 5. Build the kit directory: app.asar + build/icon.icns + installer + README.
const kitName = `VeloxaWatermarkStudio-mac-${version}`;
const kitDir  = path.join(releaseDir, kitName);
if (fs.existsSync(kitDir)) fs.rmSync(kitDir, { recursive: true, force: true });
fs.mkdirSync(path.join(kitDir, 'build'), { recursive: true });
fs.copyFileSync(asarSrc, path.join(kitDir, 'app.asar'));
fs.copyFileSync(icnsPath, path.join(kitDir, 'build', 'icon.icns'));
fs.writeFileSync(path.join(kitDir, 'veloxa-mac-installer.sh'), installerSrc, { mode: 0o755 });

const readme = `Veloxa Watermark Studio for macOS — v${version}
================================================

This kit assembles a working Veloxa Watermark Studio.app on your Mac. The
runtime download and final stitching has to happen on macOS itself because
the Electron framework relies on Unix symlinks that the Windows host can't
create directly.

Quick install (one command in Terminal):

    cd ${kitName}
    bash veloxa-mac-installer.sh

The script will:
  1. Detect your Mac's CPU (Intel x64 / Apple Silicon arm64)
  2. Download the Electron v${ELECTRON_VERSION} runtime from the official
     electronjs.org release CDN (cached in ~/Library/Caches/veloxa-electron
     so re-installs are instant)
  3. Drop the Veloxa app code (app.asar) into the .app bundle
  4. Set the icon, app name, and bundle id
  5. Strip the Gatekeeper quarantine flag so macOS will let you launch it

When it finishes you'll have:

    ${kitName}/Veloxa Watermark Studio.app

Move it to /Applications and double-click, or:
    open "Veloxa Watermark Studio.app"

If macOS warns "Veloxa Watermark Studio cannot be opened because the
developer cannot be verified": this is normal because the build is not
code-signed (signing requires an Apple Developer ID; we ship unsigned).
Right-click the .app → Open → click Open in the dialog. One-time step.

Convert-to-PDF on macOS:
  - LibreOffice (recommended): https://www.libreoffice.org/download/download/
    Install it, and the app will auto-detect 'soffice' in Settings → PDF.
  - Microsoft Office on macOS: not supported by this build (Office COM is
    a Windows-only API). Use LibreOffice.

Source / report issues:
  https://github.com/khurram5509/Veloxa-Watermark-Studio
`;
fs.writeFileSync(path.join(kitDir, 'README-mac.txt'), readme);

// 6. tar.gz the kit. Windows 10/11 ships tar.exe; the project dir contains
//    spaces, so we set cwd=releaseDir and pass relative names — that way
//    spawn doesn't have to forward a quoted absolute path through the shell.
const outTarName = `${kitName}.tar.gz`;
const outTar = path.join(releaseDir, outTarName);
try { fs.unlinkSync(outTar); } catch {}
console.log('');
console.log(`▸ Archiving ${outTar}`);
run('tar', ['-czf', outTarName, kitName], { cwd: releaseDir });
const sz = (fs.statSync(outTar).size / 1024 / 1024).toFixed(1);
console.log(`✔ Wrote ${outTar} (${sz} MB)`);

// 7. Cleanup the staging dirs we used to produce the asar — keep just the tar.gz.
try { fs.rmSync(winOut, { recursive: true, force: true }); } catch {}
try { fs.rmSync(kitDir, { recursive: true, force: true }); } catch {}

console.log('');
console.log('macOS distribution kit ready.');
console.log('');
console.log(`Upload ${path.basename(outTar)} to the v${version} GitHub release as a Mac download.`);
console.log('');
console.log('To test on a Mac:');
console.log(`  tar -xzf ${path.basename(outTar)}`);
console.log(`  cd ${kitName}`);
console.log('  bash veloxa-mac-installer.sh');
console.log('  open "Veloxa Watermark Studio.app"');
} // end continueBuild
